### ISSUE TITLE
在ITQ中cifar 10原数据到最后cifar_10yunchao.mat是如何得到的？

### ISSUE THREAD

**Issue by mingminzhen** [willard-yuan/hashing-baseline-for-image-retrieval#1]
如题

**Comment by willard-yuan** [comment]
yunchao gong的这个提取的320维gist他论文里有讲怎么弄的，不过我没实现出来，我现在用gist都直接用的gist特征提取代码提取的512维的特征，也非常的好用。

**Comment by mingminzhen** [comment]
所以你给的gist_320d_CIFAR-10_yunchao.mat是直接用的gist特征提取算法提取512维特征，然后取的前320维吗？

**Comment by willard-yuan** [comment]
不是的，`gist_320d_CIFAR-10_yunchao.mat`是yunchao gong的，这个可以直接用。如果你自己用gist特征代码提取gist特征，提取的512维特征直接就作为512维的gist特征了，你那种“取的前320维”是错误了。

你完全没必要非得弄个320维的gist特征，512的gist在很多论文里也很常见。

**Comment by mingminzhen** [comment]
好的，明白了！方便加你qq吗？我qq是624237402，目前在北大读硕士，有些图像检索的问题想跟你探讨下。

**Comment by willard-yuan** [comment]
已经加了。

2015-07-14 23:53 GMT+08:00 mingminzhen notifications@github.com:

**Comment by sunyinhui** [comment]
hi,怎么跑我的实验数据，需要生成像cifar-10的Matlab格式吗？？？

**Comment by willard-yuan** [comment]
@sunyinhui 对的，cifar-10里保存的是从cifar-10图像上提取的特征，你如果要跑自己的图像集，只需要像它一样，提取你的图像特征然后保存为.mat格式既可。

**Comment by sunyinhui** [comment]
恩，好的，我试下，谢谢啦

**Comment by icycai** [comment]
320维的 Gist 特征应该是用 3 个尺度，每个尺度 [8 8 4] 个方向跑的数据吧，所以维数是（8+8+4）_4_4 = 320
