### ISSUE TITLE
关于数据集训练的问题

### ISSUE THREAD

**Issue by liangdwuoi** [willard-yuan/hashing-baseline-for-image-retrieval#12]
我在构建KD树索引时有一个内存占用问题，把sift特征提取出来，全部放在一个矩阵里，给KD树构建，这样的后果是，当我的训练集超过200张时，电脑内存（8G）已经不够用了。
所以，我想问的是，hash索引构建的时候会有这样类似的内存占用问题吗？

**Comment by willard-yuan** [comment]
用LSH不会面临这样的问题，其他的要看哈希的过程，比如有的里面涉及到对全部的数据做矩阵相乘等，这些都需要把数据都读入进去。
