### ISSUE TITLE
What is BPH？

### ISSUE THREAD

**Issue by zerteen** [willard-yuan/hashing-baseline-for-image-retrieval#15]

**Comment by willard-yuan** [comment]
@zerteen Sorry for later reply. BPH is a method just for idea,  and you can refer to the paper of Latent Semantic Minimal Hashing for Image Retrieval. It's two years since I graduated. Something about details may be not clear Now.

**Comment by zerteen** [comment]
@willard-yuan  Greatly appreciate your answering.
