### ISSUE TITLE
实验结果差请问有哪些可能的原因

### ISSUE THREAD

**Issue by Wayne-Yuan** [willard-yuan/hashing-baseline-for-image-retrieval#18]
您好，我直接使用神经网络提取的2048d的特征进行图像最近邻搜索的mAP差不多90%，但是很费时间，所以考虑采用hash来缩短时间。将特征导成mat文件后运行了您的代码，采用了几个hash方法，实验编码效果，但是效果都不太好。所以想问问您可能是什么原因导致的。

我考虑的可能原因有
1）数据归一化，我实验了归一化和不归一化的结果，都不是特别好。我看了的cal256-1024dCNN的特征的统计数据，发现您数据的均值和方差都特别小，不知道您是怎么处理的。
2）数据在特征空间的分布，但是不晓得该怎么直观的看到您的cnn特征分布和我的有什么区别。

注：我没有改动groundtruth的设置方式，仍然采用最近的k个点作为目标对象。
![pr](https://user-images.githubusercontent.com/6916275/53862454-6c352a00-4022-11e9-806e-b2e9d7cdb805.jpg)
![p-nr](https://user-images.githubusercontent.com/6916275/53862458-70614780-4022-11e9-8d23-591b1c4e8356.jpg)
![r-nr](https://user-images.githubusercontent.com/6916275/53862460-722b0b00-4022-11e9-9d02-f853f81ef006.jpg)
![map with bits](https://user-images.githubusercontent.com/6916275/53862474-75be9200-4022-11e9-8939-b66f081ecdbc.jpg)

**Comment by willard-yuan** [comment]
@Wayne-Yuan 你用的什么方式归一化的？HABIR里面有对数据做中心化处理。另外你可以先对特征做L2归一化处理。

如果要在工程中做索引，推荐使用OPQ之类的PQ索引，或者HNSW，具体介绍请阅读博客[OPQ索引与HNSW索引](http://yongyuan.name/blog/opq-and-hnsw.html)。希望能帮助到你。
