### ISSUE TITLE
mAP的源码实现问题

### ISSUE THREAD

**Issue by chenshen03** [willard-yuan/hashing-baseline-for-image-retrieval#19]
图像检索中mAP的定义应该是这篇博客所述：[图像检索 - 评价指标](https://blog.csdn.net/zziahgf/article/details/78184718)。
但是看了下代码，发现recall和precision的实现，都是以汉明距离从小到大为索引去计算的，而不是以样本位置去计算。另外，mAP的代码area_RP.m回的是precision-recall的面积（每一小块梯形面积的总和）。虽然这样计算和严格mAP定义计算得到的结果相差不多，但是依然会存在一定的误差。

**Comment by willard-yuan** [comment]
@chenshen03 汉明距离从小到大为索引，里面是对应到了汉明距离从小到大排序的。另外MAP是precision-recall曲线包围的面积，这个是没问题的，在具体操作的时候，将其划分成很多小梯形累积求和，这种方式是合理的，在ITQ里面有先例的。

希望对你有帮助。

**Comment by chenshen03** [comment]
谢谢你的耐心回答，问题已解决。
