### ISSUE TITLE
如何用自己的数据集进行实验呢

### ISSUE THREAD

**Issue by fantasy4335** [willard-yuan/hashing-baseline-for-image-retrieval#20]
数据输入应该是什么样的

**Comment by willard-yuan** [comment]
输入数据就是你提取的图像特征，可以对特征做L2归一化，然后再用[construct_data.m](https://github.com/willard-yuan/hashing-baseline-for-image-retrieval/blob/master/utils/construct_data.m)这个脚本做下预处理就可以了。

**Comment by yangzihong818** [comment]
您好，想问用construct_data.m这个处理数据集的时候，一些参数需要更改吗？因为我用一个数据集的两个特征得到的MAP几乎一样，所以我觉得我可能没有正确使用您的构造方法
