### ISSUE TITLE
Not able to download .mat files from the location specified

### ISSUE THREAD

**Issue by brevathisekar** [willard-yuan/hashing-baseline-for-image-retrieval#4]

**Comment by willard-yuan** [comment]
@brevathisekar The .mat files can be downloaded from the following addresses:

cnn_1024d_Caltech-256 download：[cnn_1024d_Caltech-256.mat](http://pan.baidu.com/s/1o67k5RG)
gist_512d_Caltech-256 download：[gist_512d_Caltech-256.mat](http://pan.baidu.com/s/1jG8ECZW)
cnn_4096d_Caltech-256 download：[cnn_4096d_Caltech-256.mat](http://pan.baidu.com/s/1eQIWkro)
gist_320d_CIFAR-10_yunchao download：[gist_320d_CIFAR-10_yunchao.mat](http://pan.baidu.com/s/1o61KSQI)

Do you mean you can't get access to these addresses?

**Comment by brevathisekar** [comment]
able to access the addresses, but for the first file of size 79MB, only 256KB shortcut is downloaded which on execution of main demo.m does not recognize as .mat file

**Comment by willard-yuan** [comment]
@brevathisekar It's OK when I test to download it. Maybe it's your Internet problem. You can try the other three datasets.

**Comment by brevathisekar** [comment]
Other datasets are also not getting downloaded. Kindly specify other site or in github itself if possible?? or specify the way to obtain the .mat file through matlab.

**Comment by willard-yuan** [comment]
@brevathisekar Can you get access to Google Cloud Drive? I can upload the datasets to Google Cloud Drive.

**Comment by brevathisekar** [comment]
Yes, i have access to Google Drive. Please upload.Thanks in advance.

**Comment by brevathisekar** [comment]
Have you uploaded in google drive? Kindly specify the link.

**Comment by willard-yuan** [comment]
@brevathisekar Sorry for later reply. I have uploaded two datasets to Google Drive, and you can download these from the follow address:
[cnn_1024d_Caltech-256.mat](https://drive.google.com/open?id=0B41p0MDWWhL7dHJsOHc2WE1sbG8)
[gist_320d_CIFAR-10_yunchao.mat](https://drive.google.com/open?id=0B41p0MDWWhL7cG8tak1OOE5VTWM)
