### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by hlzz** [willard-yuan/hashing-baseline-for-image-retrieval#5]
This benchmark repo is magnificent. I am actually thinking of importing some robust hashing-based methods into [libvot](https://github.com/hlzz/libvot/blob/feature/Roadmap.md) in c/c++, used for production. Do you have some suggestions? This repo is definitely a valuable reference for me 👍

**Comment by willard-yuan** [comment]
I'm not sure whether it's helpful for **libvot** since vocabulary tree is fast for image search. Adding hashing method for fast index will make **libvot** become complex. But if you really want to use hashing method for fast search index, I think LSH and ITQ are good choices.

**Comment by hlzz** [comment]
@willard-yuan great. libvot don't need to focus only on vocabulary tree method. I'd like it to be a general toolbox for image retrieval. :) We can do hashing methods as a separate module of course. LSH would be good. Thanks for the suggestion!
