### ISSUE TITLE
Excuse me! I find a silly bug in your code!

### ISSUE THREAD

**Issue by leijiezhang** [willard-yuan/hashing-baseline-for-image-retrieval#8]

**Comment by willard-yuan** [comment]
Hi @leijiezhang, thanks for report the bug. I have updated the `demo.m` and `construct_data.m` by uncommenting the corresponding line [L98](https://github.com/willard-yuan/hashing-baseline-for-image-retrieval/blob/master/utils/construct_data.m#L98) and [L21](https://github.com/willard-yuan/hashing-baseline-for-image-retrieval/blob/master/demo.m#L21). I think it will be OK. If there is any other bugs, feel free to report.
